
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace Releasemanagment
{

using System;
    using System.Collections.Generic;
    
public partial class Developer
{

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
    public Developer()
    {

        this.Testers = new HashSet<Tester>();

    }


    public int Developer_id { get; set; }

    public string Developer_name { get; set; }

    public Nullable<int> TeamLead_id { get; set; }

    public Nullable<int> Module_id { get; set; }

    public string Module_status { get; set; }



    public virtual Module Module { get; set; }

    public virtual TeamLead TeamLead { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<Tester> Testers { get; set; }

}

}
