
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace Releasemanagment
{

using System;
    using System.Collections.Generic;
    
public partial class Employee
{

    public int Employee_id { get; set; }

    public string Employee_name { get; set; }

    public string Employee_role { get; set; }

}

}
