
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace Releasemanagment
{

using System;
    using System.Collections.Generic;
    
public partial class Project
{

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
    public Project()
    {

        this.TeamLeads = new HashSet<TeamLead>();

    }


    public int Project_id { get; set; }

    public string Project_name { get; set; }

    public string Project_Status { get; set; }

    public string Project_Type { get; set; }



    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<TeamLead> TeamLeads { get; set; }

}

}
