
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace Releasemanagment
{

using System;
    using System.Collections.Generic;
    
public partial class Tester
{

    public int Tester_id { get; set; }

    public string Tester_name { get; set; }

    public string Testing_status { get; set; }

    public Nullable<int> Module_id { get; set; }

    public Nullable<int> Developer_id { get; set; }



    public virtual Developer Developer { get; set; }

    public virtual Module Module { get; set; }

}

}
